### ISSUE TITLE
Win 10 ignoring overclock setting in UEFI

### ISSUE THREAD

**Issue by stanton2** [pftf/RPi4#160] opened 2021-07-07 16:41 UTC
I'm running a RPi 4b with 8GHz RAM.
I've been told to overclock using Raspberry OS first, via boot/config/txt.  Then insert the Win10 sd card and configure the UEFI to show the same overclock.
The overclock to 2 GHz using Raspberry OS works perfectly and the "watch" command displays cpu speeds varying between 600 MHz and 2 GHz with load.
However, the saved cpu configuration of 2 GHz  in the UEFI is not reflected in the Task Manager, which continues to display 1.5 GHz as the base speed
This is my first attempt on Github, so trust that the information provided is meaningful.
Thank you in advance for any assistance provided.
Adrian

**Comment by samerhaj** [comment] 2021-07-07 17:40
This is duplicate of #39

**Comment by samerhaj** [comment] 2021-07-17 13:13
Closing as duplicate

**Closed by samerhaj** 2021-07-17 13:13 UTC
