### ISSUE TITLE
Question: Why don't you provide the pkg having 3 GB Mem limit disabled?

### ISSUE THREAD

**Issue by Gatsby-Lee** [pftf/RPi4#245] opened 2023-10-03 21:14 UTC
Hello,

It's just a question.
As you described in the description, the 3 GB Mem ( by default ) limit can be disabled manually.
I can do that manually.

I am wondering if you can provide another pkg that disables 3GB Mem limit by default, so people don't need to fork this repo and apply their own patch to handle it.

Thank you
Gatsby

**Comment by pbatard** [comment] 2023-10-03 21:17
Duplicate of #175.

**Closed by pbatard** 2023-10-03 21:17 UTC
