### ISSUE TITLE
RPi4, USB-MSB context, no microsd card: What is the intent? FYI: What v1.16 does.

### ISSUE THREAD

**Issue by markmi** [pftf/RPi4#77] opened 2020-06-23 22:41 UTC
USB-MSB for the RPi4 is now in stable instead of beta. Just to see what the status was for attempting its use I tried setting up for booting without a microsd card. v1.16 hung-up. Using a debug RPI_EFI.fd showed:

```
UEFI firmware (version UEFI Firmware v1.16 (DEBUG) built at 12:15:58 on Jun 18 2020)
. . . (omitted) . . .
add-symbol-file /home/appveyor/projects/rpi4/Build/RPi4/DEBUG_GCC5/AARCH64/Platform/RaspberryPi/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe/DEBUG/ArasanMMCHost.dll 0x36D39000
Loading driver at 0x00036D38000 EntryPoint=0x00036D3B6AC ArasanMMCHost.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 35F3BB18
ProtectUefiImageCommon - 0x35F3B2C0
  - 0x0000000036D38000 - 0x0000000000007000
SetUefiImageMemoryAttributes - 0x0000000036D38000 - 0x0000000000001000 (0x0000000000004008)
SetUefiImageMemoryAttributes - 0x0000000036D39000 - 0x0000000000004000 (0x0000000000020008)
SetUefiImageMemoryAttributes - 0x0000000036D3D000 - 0x0000000000002000 (0x0000000000004008)
InstallProtocolInterface: 3E591C00-9E4A-11DF-9244-0002A5F5F51B 36D3D030
InstallProtocolInterface: 964E5B21-6459-11D2-8E39-00A0C969723B 35F2DBC8
InstallProtocolInterface: 09576E91-6D3F-11D2-8E39-00A0C969723B 35F2DD98
MMCSendCommand(371): MMC_CMD1 ERRI MmcStatus 0x18040
MMCSendCommand(371): MMC_CMD8 ERRI MmcStatus 0x18040
Not a SD2.0 Card
MMCSendCommand(371): MMC_CMD55 ERRI MmcStatus 0x18040
Card should be MMC
MMCSendCommand(371): MMC_CMD1 ERRI MmcStatus 0x18040
MMCSendCommand(371): MMC_CMD55 ERRI MmcStatus 0x18040
Card should be MMC
MMCSendCommand(371): MMC_CMD1 ERRI MmcStatus 0x18040
MMCSendCommand(371): MMC_CMD55 ERRI MmcStatus 0x18040
. . . (omitted) . . .
```

The last 3 shown lines repeated, without bound? Release was silent about the problem but I expect was stuck looping the same way, just without the messages.

This was a 4 GiByte RPi4 v1.1 for the test context.

**Comment by pbatard** [comment] 2020-06-23 22:45
Duplicate of #37. This issue is tracked there. We can't provide an ETA. as to when we are going to address it.

Closing this as duplicate.

**Closed by pbatard** 2020-06-23 22:45 UTC
